apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../base
namePrefix: sample-
commonLabels:
  type: mock
  app: sample
configMapGenerator:
- files:
  - mockserver.properties
  - initializerJson.json
  name: mockerserver-config

